---

- name: Download Hyper package
  get_url:
    url: '{{ hyper_url }}'
    dest: '{{ hyper_download_target }}/{{ hyper_download_name }}'
    mode: 0700

- name: Install Hyper package
  apt:
    deb: '{{ hyper_download_target }}/{{ hyper_download_name }}'

- name:
  file:
    path: '{{ hyper_config_location }}'
    state: directory
    mode: 0755
    owner: '{{ hyper_default_user }}'
    group: '{{ hyper_default_user }}'

- name: Create .hyper.js file
  template:
    src: .hyper.js.j2
    dest: '{{ hyper_config_location }}/.hyper.js'
    owner: '{{ hyper_default_user }}'
    group: '{{ hyper_default_user }}'

