# Generic for all distro

- name: Update packages
  package:
    name: "*"
    state: latest
    update_cache: true
  register: update_info

- name: Update packages output
  debug:
      msg: "{{ update_info.stdout_lines }}"
  
