---

- name: Install packages via roles
  hosts: localhost
  become: true
  roles:
    - roles/generic-packages
    - roles/snapd
    - roles/flatpak
    # Gaming
    - roles/wine
    - roles/lutris
    - roles/steam
    # Apps
    - roles/vscode
    - roles/discord
    - roles/spotify
    # DevTools
    - roles/docker
    - roles/vim
    - role: hyper
      vars:
        hyper_install: true

