---

- name: Install packages via roles
  hosts: localhost
  become: true
  roles:
    - roles/generic-packages
    # Gaming
    - roles/snapd
    - roles/wine
    - roles/lutris
    - roles/steam
    # Apps
    - roles/discord
    - roles/spotify