---
# NOTE(Liam):
#   Any roles with '# Clean' next to them are present purely to remove an prior installations
#

- name: Install packages via roles
  hosts: localhost
  become: true
  roles:
    - roles/generic-packages
    - roles/snapd
    - roles/flatpak
    # Apps
    - roles/vscode
    - roles/discord
    - roles/spotify
    # DevTools
    - roles/docker
    - roles/vim
    - roles/hyper # Clean

