---

- name: Perform patching
  hosts: all
  become: true
  roles:
    - role: roles/generic-packages
      vars:
        packages: [
            atop,
            htop,
            screen,
            git
        ]
    - roles/patching
