---

- name: Configure picluster
  hosts: picluster
  become: true
  roles:
    - roles/generic-packages
    - roles/snapd
    - role: roles/vim
      vars:
        v_default_user: "pi"
    - roles/patching
    - roles/raspi-boot
