---
# Debian
- name: Install snapd
  apt:
    name: snapd
    state: present
    update_cache: true
  when: ansible_facts['os_family']|lower == 'debian'

# RHEL
- name: Install snapd
  yum:
    name: snapd
    state: present
    update_cache: true
  when: ansible_facts['os_family']|lower == 'redhat'