---
# Debian
- name:
  block:
  - name: Add multiverse repo to apt
    apt_repository:
      repo: "deb http://archive.ubuntu.com/ubuntu/ {{ansible_lsb.codename | lower}} multiverse"
      state: present

  - name: Install steam
    apt:
      name: steam
      state: present
      update_cache: true

  when: ansible_facts['os_family']|lower == 'debian'

# RHEL
- name: Failed to install steam
  debug:
    msg: Cannot install steam on RHEL, Update role to support it!
  when: ansible_facts['os_family']|lower == 'redhat'