---
# Debian

- name: Add generic packages repos
  apt_repository:
      repo: "{{ item }}"
      state: present
  loop: "{{ repos }}"
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install generic packages
  apt:
    pkg: "{{ packages }}"
    state: present
    update_cache: true
  when: ansible_facts['os_family']|lower == 'debian'

# RHEL
- name: Install generic packages
  yum:
    pkg: "{{ packages }}"
    state: present
    update_cache: true
  when: ansible_facts['os_family']|lower == 'redhat'