---

vim_commands: [
      "curl -sL install-node.now.sh/lts | bash"
    ]

vim_packages: [
      fzf
    ]

vim_snaps:
    - vim_snap: node
      vim_snap_channel: latest/edge

vim_pack_repos: 
    - vim_repo: "https://github.com/preservim/nerdtree.git"
      vim_nickname: "nerdtree"
    - vim_repo: "https://github.com/itchyny/lightline.vim"
      vim_nickname: "lightline"
    - vim_repo: "https://github.com/pearofducks/ansible-vim"
      vim_nickname: "ansible"

default_user: 'liam'
