---

repos: 
    - repo: "https://github.com/preservim/nerdtree.git"
      nickname: "nerdtree"
    - repo: "https://github.com/itchyny/lightline.vim"
      nickname: "lightline"

default_user: 'liam'
