---
# Debian
- name: Install flatpak
  apt:
    name: flatpak
    state: present
    update_cache: true
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install gnome-software-plugin-flatpak
  apt:
    name: gnome-software-plugin-flatpak
    state: present
    update_cache: true
  when: ansible_facts['os_family']|lower == 'debian'

# RHEL
# - name: Install flatpak
#   yum:
#     name: flatpak
#     state: present
#     update_cache: true
#   when: ansible_facts['os_family']|lower == 'redhat'
#
# - name: Install gnome-software-plugin-flatpak
#   yum:
#     name: gnome-software-plugin-flatpak
#     state: present
#     update_cache: true
#   when: ansible_facts['os_family']|lower == 'debian'
#
# Generic
- name: Add flatpak repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
