---
- name: Install Vim package
  apt:
    pkg: vim
    state: present
    update_cache: true
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install packages required by Vim packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ vim_packages }}"
  when: ansible_facts['os_family']|lower == 'debian'

# Ensure Snap is installed using snapd role
- name: Install snaps required by Vim packages
  snap:
    name: "{{ item.vim_snap }}"
    state: present
    classic: true # TODO(Liam): Needs to be controlled by the defaults, this is not applicable for all packages
    channel: "{{ item.vim_snap_channel }}"
  loop: "{{ vim_snaps }}"
  when: ansible_facts['os_family']|lower == 'debian'

- name: Create .vimrc file
  template:
    src: .vimrc.j2
    dest: "/home/{{ v_default_user }}/.vimrc"
    owner: "{{ v_default_user }}"
    group: "{{ v_default_user }}"

- name: Create Vim home directory
  changed_when: false
  file:
    path: "/home/{{ v_default_user }}/.vim"
    state: directory
    recurse: yes
    owner: "{{ v_default_user }}"
    group: "{{ v_default_user }}"
    mode: '0755'

- name: Create Vim pack directory
  changed_when: false
  file:
    path: "/home/{{ v_default_user }}/.vim/pack/vendor/start"
    state: directory
    recurse: yes
    owner: "{{ v_default_user }}"
    group: "{{ v_default_user }}"
    mode: '0755'

- name: Create pack plugin directories
  file:
    path: "/home/{{ v_default_user }}/.vim/pack/vendor/start/{{ item.vim_nickname }}"
    state: directory
    recurse: yes
    owner: "{{ v_default_user }}"
    group: "{{ v_default_user }}"
  loop: "{{ vim_pack_repos }}"

- name: Install pack plugins
  changed_when: false
  git:
    repo: "{{ item.vim_repo }}"
    dest: "/home/{{ v_default_user }}/.vim/pack/vendor/start/{{ item.vim_nickname }}"
    depth: 1
    force: true
  loop: "{{ vim_pack_repos }}"

- name: Install pip packages
  pip: 
    name: "{{ item }}"
  loop: "{{ vim_pip_packages }}"

