---
# Debian

- name: Install Vim package
  apt:
    pkg: vim
    state: present
    update_cache: true
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install packages required by Vim packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ vim_packages }}"
  when: ansible_facts['os_family']|lower == 'debian'

- name: Create .vimrc file
  template:
    src: .vimrc.j2
    dest: "/home/{{ default_user }}/.vimrc"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"

- name: Create Vim home directory
  changed_when: false
  file:
    path: "/home/{{ default_user }}/.vim/pack/vendor/start"
    state: directory
    recurse: yes
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0755'

- name: Create Plugin directories
  file:
    path: "/home/{{ default_user }}/.vim/pack/vendor/start/{{ item.vim_nickname }}"
    state: directory
    recurse: yes
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
  loop: "{{ vim_repos }}"

- name: Install plugins
  changed_when: false
  git:
    repo: "{{ item.vim_repo }}"
    dest: "/home/{{ default_user }}/.vim/pack/vendor/start/{{ item.vim_nickname }}"
    depth: 1
    force: true
  loop: "{{ vim_repos }}"

# RHEL
- name: Install generic packages
  yum:
    pkg: "{{ packages }}"
    state: present
    update_cache: true
  when: ansible_facts['os_family']|lower == 'redhat'
