---
- name: Install Vim package
  package:
    name: vim
    state: present

- name: Install packages required by Vim packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ vim_packages }}"

# Ensure Snap is installed using snapd role
- name: Install snaps required by Vim packages
  snap:
    name: "{{ item.vim_snap }}"
    state: present
    classic: true # TODO(Liam): Needs to be controlled by the defaults, this is not applicable for all packages
    channel: "{{ item.vim_snap_channel }}"
  loop: "{{ vim_snaps }}"
  when: ansible_facts['os_family']|lower == 'debian'

- name: Create .vimrc file
  template:
    src: .vimrc.j2
    dest: "{{ v_default_path }}{{ v_default_user }}/.vimrc"
    owner: "{{ v_default_user }}"
    group: "{{ v_default_group }}"

- name: Create Vim home directory
  changed_when: false
  file:
    path: "{{ v_default_path }}{{ v_default_user }}/.vim"
    state: directory
    recurse: yes
    owner: "{{ v_default_user }}"
    group: "{{ v_default_group }}"
    mode: '0755'

- name: Create Vim pack directory
  changed_when: false
  file:
    path: "{{ v_default_path }}{{ v_default_user }}/.vim/pack/vendor/start"
    state: directory
    recurse: yes
    owner: "{{ v_default_user }}"
    group: "{{ v_default_group }}"
    mode: '0755'

- name: Create pack plugin directories
  file:
    path: "{{ v_default_path }}{{ v_default_user }}/.vim/pack/vendor/start/{{ item.vim_nickname }}"
    state: directory
    recurse: yes
    owner: "{{ v_default_user }}"
    group: "{{ v_default_group }}"
  loop: "{{ vim_pack_repos }}"

- name: Add safe repository (pack plugins)
  changed_when: false
  shell: "git config --global --add safe.directory {{ v_default_path }}{{ v_default_user }}/.vim/pack/vendor/start/{{ item.vim_nickname }}"
  loop: "{{ vim_pack_repos }}"

- name: Install pack plugins
  changed_when: false
  git:
    repo: "{{ item.vim_repo }}"
    dest: "{{ v_default_path }}{{ v_default_user }}/.vim/pack/vendor/start/{{ item.vim_nickname }}"
    depth: 1
    force: true
  loop: "{{ vim_pack_repos }}"

- name: Create Vundle directory
  file:
    path: "{{ v_default_path }}{{ v_default_user }}/.vim/bundle/Vundle.vim"
    state: directory
    recurse: yes
    owner: "{{ v_default_user }}"
    group: "{{ v_default_group }}"

- name: Add safe repository (Vundle)
  changed_when: false
  shell: "git config --global --add safe.directory {{ v_default_path }}{{ v_default_user }}/.vim/bundle/Vundle.vim"

- name: Install Vundle
  changed_when: false
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ v_default_path }}{{ v_default_user }}/.vim/bundle/Vundle.vim"
    depth: 1
    force: true

- name: Correct .vim ownership
  changed_when: false
  file:
    path: "{{ v_default_path }}{{ v_default_user }}/.vim"
    state: directory
    recurse: yes
    owner: '{{ v_default_user }}'
    group: '{{ v_default_group }}'

- name: Install Vundle plugins
  changed_when: false
  become_user: '{{ v_default_user }}'
  shell: 'vim +PluginInstall +qall'
  args:
    stdin: "\n"

- name: Install vim-plug plugins
  changed_when: false
  become_user: '{{ v_default_user }}'
  shell: 'vim +PlugInstall +qall'
  args:
    stdin: "\n"

- name: Install pip packages
  pip: 
    name: "{{ item }}"
  loop: "{{ vim_pip_packages }}"

