---
# Debian
- name:
  block:
  - name: Add lutris repo to apt
    apt_repository:
      repo: ppa:lutris-team/lutris
      state: present

  - name: Install lutris
    apt:
      name: lutris
      state: present
      update_cache: true

  when: ansible_facts['os_family']|lower == 'debian'

# RHEL
- name: Failed to install lutris
  debug:
    msg: Cannot install lutris on RHEL, Update role to support it!
  when: ansible_facts['os_family']|lower == 'redhat'
