---

hyper_url: 'https://github.com/vercel/hyper/releases/download/v3.2.0/hyper_3.2.0_amd64.deb'

# Remove last '/' on hyper_download_target
hyper_download_target: '/tmp'
hyper_download_name: 'hyper.deb'

hyper_config_location: '~/.config/Hyper/.hyper.js'
hyper_default_user: 'liam'
