---
# true = install hyper | false = uninstall hyper
hyper_install: false
hyper_url: 'https://github.com/vercel/hyper/releases/download/v3.2.0/hyper_3.2.0_amd64.deb'

# Remove last '/' on hyper_download_target
hyper_download_target: '/tmp'
hyper_download_name: 'hyper.deb'

hyper_default_user: 'liam'
hyper_config_location: '/home/{{ hyper_default_user }}/.config/Hyper'

hyper_cleanup_files: ['/home/{{ hyper_default_user }}/.hyper.js']
hyper_cleanup_dirs: [
    '/home/{{ hyper_default_user }}/.config/Hyper',
    '/home/{{ hyper_default_user }}/.hyper_plugins'
  ]
